// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      _ => throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        ),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDJILOHuiCEkd7HpzNyvnbUYpDXtB1cM',
    appId: '1:534573551244:android:49442856288f20113d35a9',
    messagingSenderId: '534573551244',
    projectId: 'robot-65dac',
    storageBucket: 'robot-65dac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-6RxO54-sXJsTMgr-zHXYkvwYaHFQFK0',
    appId: '1:534573551244:ios:4492903185dcb5203d35a9',
    messagingSenderId: '534573551244',
    projectId: 'robot-65dac',
    storageBucket: 'robot-65dac.appspot.com',
    iosBundleId: 'com.example.botControl',
  );
}
